name: React Container - Kubernetes Deployment

on:
  push:
    branches: [master]

jobs:
  deploy-backstage:
    permissions:
      contents: 'read'
      id-token: 'write'

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]
    
    name: Build & Publish
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: npm install
        run: | 
          npm install
  
      - name: npm build
        run: | 
          npm run build

      - name: Build Container
        run: |-
          docker build . -t "gabsdevops/${{ github.event.repository.name }}:latest"

      - name: Push Container
        run: |-
          docker push "gabsdevops/${{ github.event.repository.name }}:latest"

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: decode kubeconfig
        run: | 
          echo ${{ secrets.KUBECONFIG }} | base64 --decode > kubeconfig
  
      - uses: azure/setup-kubectl@v3
        with:
            version: '1.23.17' # default is latest stable
        id: install
          
      - uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ./kubeconfig
          context: ${{ secrets.CLUSTER_NAME }}
        id: setcontext
