apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-web-app-kubernetes
  title: Create Simple Web App with Kubernetes (React)
  description: Create a new WebApp project
  tags:
    - react
    - webapp
    - kubernetes
spec:
  owner: web@example.com
  type: website
  parameters:
    - title: Provide some simple information
      required:
        - app_name
        - description
      properties:
        app_name:
          title: App Name
          type: string
          description: Unique name of the application
          ui:field: EntityNamePicker
        description:
          title: Description
          type: string
          description: Help others understand what this app is for.
        surge_token:
          title: Surge Token for deployment
          type: string
          description: Surge for publishing your site
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutTemplating:
          - .github/workflows/*
        values:
          app_name: ${{ parameters.app_name }}
          description: ${{ parameters.description }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}
          github_url: ${{ parameters.repoUrl }}
          team: ${{ parameters.owner }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts:
          - github.com
        description: "https://${{ parameters.app_name }}.surge.sh"
        repoUrl: ${{ parameters.repoUrl }}
        secrets:
          KUBERNETES_SECRET: ${{ parameters.surge_token }}
          IMAGE_REGISTRY: ${{ parameters.app_name }}.surge.sh
        repoVariables:
          KUBERNETES_URL: ${{ parameters.app_name }}.surge.sh

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

  output:
    links:
      - title: Go to Repository ;)
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in Backstage Catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
