name: Cloud Run Deployment Workflow

on:
  push:
    branches: [main]

env:
  PROJECT_ID: gabsdevops # TODO: update Google Cloud project id
  GAR_LOCATION: docker-registry # TODO: update Artifact Registry location
  SERVICE: dantas-stage # TODO: update Cloud Run service name
  REGION: us-central1 # TODO: update Cloud Run service region

jobs:
  deploy-backstage:
    permissions:
      contents: 'read'
      id-token: 'write'

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]
    
    name: Deploying Backstage
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3

      - uses: google-github-actions/auth@v0
        id: auth
        with:
          token_format: 'access_token'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: docker auth
        id: docker-auth
        uses: 'docker/login-action@v2'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'

        # This example runs "docker login" directly to Artifact Registry.
      - name: docker login
        run: |-
          echo '${{ steps.auth.outputs.access_token }}' | docker login -u oauth2accesstoken --password-stdin https://${{ env.REGION }}-docker.pkg.dev

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
  
      - name: yarn install
        uses: backstage/actions/yarn-install@v0.6.4
        with:
          cache-prefix: ${{ runner.os }}-v${{ matrix.node-version }}
  
      - name: yarn tsc
        run: | 
          yarn tsc

      - name: yarn lint
        run: | 
          yarn lint

      - name: yarn build
        run: | 
          yarn build:all
          ls
      
      - name: Build Container
        run: |-
          docker build . -f packages/backend/Dockerfile -t "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_LOCATION }}/${{ env.SERVICE }}"

      - name: Push Container
        run: |-
          docker push "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_LOCATION }}/${{ env.SERVICE }}"

      - name: 'deploy cloud-run'
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          image: '${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_LOCATION }}/${{ env.SERVICE }}'
          service: '${{ env.SERVICE }}'
          flags: --ingress all
          env_vars: |
              GH_PAT_TOKEN=${{ secrets.GH_PAT_TOKEN }}

      - name: Enabling all traffic to cloud run
        run: |-
          gcloud run services add-iam-policy-binding ${{ env.SERVICE }} \
          --member="allUsers" \
          --role="roles/run.invoker" \
          --region=${{ env.REGION }}
